spring.application.name=splitwise-clone

server.servlet.context-path=/v1/api

# ===============================
# Server
# ===============================
server.port=8081

# ===============================
# Datasource (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/splitwise-clone
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=splitwise_clone

# ===============================
# Connection Pool (HikariCP - default)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# Flyway (optional)
# ===============================
# spring.flyway.enabled=true
# spring.flyway.locations=classpath:db/migration

# ===============================
# Actuator (optional)
# ===============================
# management.endpoints.web.exposure.include=health,info


logging.level.org.springframework.security=DEBUG

